### ISSUE TITLE
saving binary weight

### ISSUE THREAD

**Issue by binzzheng** [1adrianb/binary-networks-pytorch#6]
Hello, thanks for your great work! In theory, binary network can achieve 32x reduction of the network parameters. I try to save the binarized weights and the corresponding alpha list. The best way I can think of is to convert the binarized weights to bool values ​​and save them. However, each weight still requires one byte. This resulted in a model size reduction of only 4x. I would like to ask if there is any way you can save the binarized network, or any suggestions?

**Comment by 1adrianb** [comment]
Hi @binzzheng,

The 32x compression is with respect to float32. If you are comparing it with an int8 model, than indeed the compression rate will be only 8x. Note that this would be the case if no other non-binary parameters are present (which in practice its unlikely to be the case).

In your case it sounds like you are directly casting a float32 binary value to int8, hence the 4x compression. To achieve the compressions rate mentioned above you will have to perform some bit-packing. While you could do this in pytorch too, this is unlike to be very efficient. There is one issue in pytorch that actually looks into implementing something alike: https://github.com/pytorch/ao/issues/292 

You can see some CUDA code that does this here: https://github.com/1adrianb/bnn.torch/blob/master/BinarySpatialConvolution.cu

**Comment by binzzheng** [comment]
I see, thanks for your reply. All the best！
